# Code generated by sdk/gen/gen_clients.py. DO NOT EDIT.
from __future__ import annotations

from typing import Any

from dogabot_sdk._types import JsonValue, RequestOptions

OPERATION_IDS: tuple[str, ...] = (
    "getMe",
    "getMeStatistics",
    "getMePositions",
    "getMePositionlegs",
    "getMeOrders",
    "getMeSignals",
    "getMeEmitters",
    "postMeEmittersSummary",
    "postAutomationsSummary",
    "getFollowers",
    "postFollowers",
    "getFollowersById",
    "patchFollowersById",
    "deleteFollowersById",
    "postFollowersSummary",
    "getFollowersSummaryById",
    "getFollowersPnlseriesById",
    "getFollowersPositionById",
    "getBots",
    "postBots",
    "getBotsById",
    "patchBotsById",
    "deleteBotsById",
    "postBotsSummary",
    "getBotsPnlseriesById",
    "getBotsPositionById",
    "getEmitters",
    "postEmitters",
    "getEmittersById",
    "patchEmittersById",
    "deleteEmittersById",
    "postEmittersSummary",
    "getEmittersSummaryById",
    "getEmittersCurated",
    "getEmittersPnlseriesById",
    "getEmittersPositionById",
    "getPortfolios",
    "postPortfolios",
    "getPortfoliosById",
    "patchPortfoliosById",
    "deletePortfoliosById",
    "postPortfoliosSummary",
    "getPortfoliosPnlseriesById",
    "getPortfoliosPositionsById",
    "getOrders",
    "getSignals",
    "getBacktestQuota",
    "getBacktests",
    "getBacktestsSummary",
    "getBacktestByJob_id",
    "getBacktestSignalsByJob_id",
    "getBacktestBulkSeed",
    "getBacktestBulkBatches",
    "getBacktestBulkBatchesByBatch_id",
    "getTicker",
    "getFundingrate",
    "getMarketOrderbook",
    "getMarketTrades",
    "getMarkets",
    "getMarketsAssetprofile",
    "getExchanges",
    "getMarkettypes",
    "getMarketplaceSearch",
    "getMarketplaceSellersByHandle",
    "getDatafeedHistory",
    "postMarketsSymbolcorrelation",
    "postMarketsSymbolvolatility",
    "postMarketsSymbolfeebreakeven",
    "getTerminalOrders",
    "getTerminalOrdersByclientorderidByClient_order_id",
    "getTerminalPositions",
    "getTerminalSymbolrules",
    "getTerminalOrdercapabilities",
    "getExchangeBalances",
    "getExchangePositions",
    "getExchangeMarginsummary",
    "getExchangeOrders",
    "getExchangeTrades",
    "getExchangeIncome",
    "getExchangeOpenablenotional",
    "postExchangeLeverage",
    "postExchangeCancelorder",
    "postExchangeCancelorders",
    "getCredentials",
    "postCredentials",
    "getTags",
    "postTags",
    "getMeStatisticsBytag",
    "postFollowersStartById",
    "postFollowersStopById",
    "postBotsStartById",
    "postBotsStopById",
    "postBotsBooksById",
    "postFollowersBooksById",
    "postEmittersStartById",
    "postEmittersStopById",
    "postPortfoliosStartById",
    "postPortfoliosStopById",
    "putFollowersTagsById",
    "putBotsTagsById",
    "putEmittersTagsById",
    "putPortfoliosTagsById",
    "patchTagsById",
    "deleteTagsById",
    "putCredentialsById",
    "deleteCredentialsById",
    "postCredentialsDefaultById",
    "postBacktest",
    "postBacktestBulk",
    "postBacktestBulkBatchesRerunByBatch_id",
    "postBacktestBulkBatchesCancelByBatch_id",
    "postBacktestCancelByJob_id",
    "postTerminalPlaceorder",
    "postTerminalCancelorder",
    "getAiChatQuota",
    "getAiChatConversations",
    "postAiChatConversations",
    "getAiChatConversationsById",
    "postAiChatConversationsMessagesById",
    "postAiChatConversationsToolsConfirmByIdCall_id",
)


class Resources:
    """All OpenAPI operationIds as client methods."""

    def __init__(self, client: Any) -> None:
        self._client = client

    def get_me(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/me"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_me_statistics(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/me/statistics"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_me_positions(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/me/positions"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_me_positionlegs(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/me/position-legs"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_me_orders(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/me/orders"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_me_signals(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/me/signals"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_me_emitters(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/me/emitters"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def post_me_emitters_summary(self, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/me/emitters/summary"
        return self._client.request(
            method="POST",
            path=path,
            body=body,
            options=options,
        )

    def post_automations_summary(self, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/automations/summary"
        return self._client.request(
            method="POST",
            path=path,
            body=body,
            options=options,
        )

    def get_followers(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/followers"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def post_followers(self, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/followers"
        return self._client.request(
            method="POST",
            path=path,
            body=body,
            write=True,
            options=options,
        )

    def get_followers_by_id(self, id: str | int, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/followers/{id}".format(id=id)
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def patch_followers_by_id(self, id: str | int, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/followers/{id}".format(id=id)
        return self._client.request(
            method="PATCH",
            path=path,
            body=body,
            write=True,
            options=options,
        )

    def delete_followers_by_id(self, id: str | int, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/followers/{id}".format(id=id)
        return self._client.request(
            method="DELETE",
            path=path,
            body=body,
            write=True,
            options=options,
        )

    def post_followers_summary(self, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/followers/summary"
        return self._client.request(
            method="POST",
            path=path,
            body=body,
            options=options,
        )

    def get_followers_summary_by_id(self, id: str | int, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/followers/summary/{id}".format(id=id)
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_followers_pnlseries_by_id(self, id: str | int, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/followers/{id}/pnl-series".format(id=id)
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_followers_position_by_id(self, id: str | int, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/followers/{id}/position".format(id=id)
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_bots(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/bots"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def post_bots(self, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/bots"
        return self._client.request(
            method="POST",
            path=path,
            body=body,
            write=True,
            options=options,
        )

    def get_bots_by_id(self, id: str | int, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/bots/{id}".format(id=id)
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def patch_bots_by_id(self, id: str | int, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/bots/{id}".format(id=id)
        return self._client.request(
            method="PATCH",
            path=path,
            body=body,
            write=True,
            options=options,
        )

    def delete_bots_by_id(self, id: str | int, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/bots/{id}".format(id=id)
        return self._client.request(
            method="DELETE",
            path=path,
            body=body,
            write=True,
            options=options,
        )

    def post_bots_summary(self, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/bots/summary"
        return self._client.request(
            method="POST",
            path=path,
            body=body,
            options=options,
        )

    def get_bots_pnlseries_by_id(self, id: str | int, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/bots/{id}/pnl-series".format(id=id)
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_bots_position_by_id(self, id: str | int, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/bots/{id}/position".format(id=id)
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_emitters(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/emitters"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def post_emitters(self, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/emitters"
        return self._client.request(
            method="POST",
            path=path,
            body=body,
            write=True,
            options=options,
        )

    def get_emitters_by_id(self, id: str | int, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/emitters/{id}".format(id=id)
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def patch_emitters_by_id(self, id: str | int, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/emitters/{id}".format(id=id)
        return self._client.request(
            method="PATCH",
            path=path,
            body=body,
            write=True,
            options=options,
        )

    def delete_emitters_by_id(self, id: str | int, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/emitters/{id}".format(id=id)
        return self._client.request(
            method="DELETE",
            path=path,
            body=body,
            write=True,
            options=options,
        )

    def post_emitters_summary(self, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/emitters/summary"
        return self._client.request(
            method="POST",
            path=path,
            body=body,
            options=options,
        )

    def get_emitters_summary_by_id(self, id: str | int, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/emitters/summary/{id}".format(id=id)
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_emitters_curated(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/emitters/curated"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_emitters_pnlseries_by_id(self, id: str | int, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/emitters/{id}/pnl-series".format(id=id)
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_emitters_position_by_id(self, id: str | int, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/emitters/{id}/position".format(id=id)
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_portfolios(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/portfolios"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def post_portfolios(self, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/portfolios"
        return self._client.request(
            method="POST",
            path=path,
            body=body,
            write=True,
            options=options,
        )

    def get_portfolios_by_id(self, id: str | int, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/portfolios/{id}".format(id=id)
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def patch_portfolios_by_id(self, id: str | int, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/portfolios/{id}".format(id=id)
        return self._client.request(
            method="PATCH",
            path=path,
            body=body,
            write=True,
            options=options,
        )

    def delete_portfolios_by_id(self, id: str | int, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/portfolios/{id}".format(id=id)
        return self._client.request(
            method="DELETE",
            path=path,
            body=body,
            write=True,
            options=options,
        )

    def post_portfolios_summary(self, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/portfolios/summary"
        return self._client.request(
            method="POST",
            path=path,
            body=body,
            options=options,
        )

    def get_portfolios_pnlseries_by_id(self, id: str | int, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/portfolios/{id}/pnl-series".format(id=id)
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_portfolios_positions_by_id(self, id: str | int, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/portfolios/{id}/positions".format(id=id)
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_orders(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/orders"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_signals(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/signals"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_backtest_quota(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/backtest/quota"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_backtests(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/backtests"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_backtests_summary(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/backtests/summary"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_backtest_by_job_id(self, job_id: str | int, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/backtest/{job_id}".format(job_id=job_id)
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_backtest_signals_by_job_id(self, job_id: str | int, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/backtest/{job_id}/signals".format(job_id=job_id)
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_backtest_bulk_seed(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/backtest/bulk/seed"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_backtest_bulk_batches(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/backtest/bulk/batches"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_backtest_bulk_batches_by_batch_id(self, batch_id: str | int, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/backtest/bulk/batches/{batch_id}".format(batch_id=batch_id)
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_ticker(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/ticker"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_fundingrate(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/funding-rate"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_market_orderbook(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/market/orderbook"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_market_trades(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/market/trades"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_markets(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/markets"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_markets_assetprofile(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/markets/asset-profile"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_exchanges(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/exchanges"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_markettypes(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/market-types"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_marketplace_search(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/marketplace/search"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_marketplace_sellers_by_handle(self, handle: str | int, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/marketplace/sellers/{handle}".format(handle=handle)
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_datafeed_history(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/datafeed/history"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def post_markets_symbolcorrelation(self, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/markets/symbol-correlation"
        return self._client.request(
            method="POST",
            path=path,
            body=body,
            options=options,
        )

    def post_markets_symbolvolatility(self, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/markets/symbol-volatility"
        return self._client.request(
            method="POST",
            path=path,
            body=body,
            options=options,
        )

    def post_markets_symbolfeebreakeven(self, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/markets/symbol-fee-breakeven"
        return self._client.request(
            method="POST",
            path=path,
            body=body,
            options=options,
        )

    def get_terminal_orders(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/terminal/orders"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_terminal_orders_byclientorderid_by_client_order_id(self, client_order_id: str | int, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/terminal/orders/by-client-order-id/{client_order_id}".format(client_order_id=client_order_id)
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_terminal_positions(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/terminal/positions"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_terminal_symbolrules(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/terminal/symbol-rules"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_terminal_ordercapabilities(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/terminal/order-capabilities"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_exchange_balances(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/exchange/balances"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_exchange_positions(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/exchange/positions"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_exchange_marginsummary(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/exchange/margin-summary"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_exchange_orders(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/exchange/orders"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_exchange_trades(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/exchange/trades"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_exchange_income(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/exchange/income"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_exchange_openablenotional(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/exchange/openable-notional"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def post_exchange_leverage(self, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/exchange/leverage"
        return self._client.request(
            method="POST",
            path=path,
            body=body,
            write=True,
            options=options,
        )

    def post_exchange_cancelorder(self, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/exchange/cancel-order"
        return self._client.request(
            method="POST",
            path=path,
            body=body,
            write=True,
            options=options,
        )

    def post_exchange_cancelorders(self, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/exchange/cancel-orders"
        return self._client.request(
            method="POST",
            path=path,
            body=body,
            write=True,
            options=options,
        )

    def get_credentials(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/credentials"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def post_credentials(self, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/credentials"
        return self._client.request(
            method="POST",
            path=path,
            body=body,
            write=True,
            options=options,
        )

    def get_tags(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/tags"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def post_tags(self, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/tags"
        return self._client.request(
            method="POST",
            path=path,
            body=body,
            write=True,
            options=options,
        )

    def get_me_statistics_bytag(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/me/statistics/by-tag"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def post_followers_start_by_id(self, id: str | int, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/followers/{id}/start".format(id=id)
        return self._client.request(
            method="POST",
            path=path,
            write=True,
            options=options,
        )

    def post_followers_stop_by_id(self, id: str | int, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/followers/{id}/stop".format(id=id)
        return self._client.request(
            method="POST",
            path=path,
            write=True,
            options=options,
        )

    def post_bots_start_by_id(self, id: str | int, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/bots/{id}/start".format(id=id)
        return self._client.request(
            method="POST",
            path=path,
            write=True,
            options=options,
        )

    def post_bots_stop_by_id(self, id: str | int, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/bots/{id}/stop".format(id=id)
        return self._client.request(
            method="POST",
            path=path,
            write=True,
            options=options,
        )

    def post_bots_books_by_id(self, id: str | int, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/bots/{id}/books".format(id=id)
        return self._client.request(
            method="POST",
            path=path,
            body=body,
            write=True,
            options=options,
        )

    def post_followers_books_by_id(self, id: str | int, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/followers/{id}/books".format(id=id)
        return self._client.request(
            method="POST",
            path=path,
            body=body,
            write=True,
            options=options,
        )

    def post_emitters_start_by_id(self, id: str | int, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/emitters/{id}/start".format(id=id)
        return self._client.request(
            method="POST",
            path=path,
            write=True,
            options=options,
        )

    def post_emitters_stop_by_id(self, id: str | int, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/emitters/{id}/stop".format(id=id)
        return self._client.request(
            method="POST",
            path=path,
            write=True,
            options=options,
        )

    def post_portfolios_start_by_id(self, id: str | int, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/portfolios/{id}/start".format(id=id)
        return self._client.request(
            method="POST",
            path=path,
            write=True,
            options=options,
        )

    def post_portfolios_stop_by_id(self, id: str | int, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/portfolios/{id}/stop".format(id=id)
        return self._client.request(
            method="POST",
            path=path,
            write=True,
            options=options,
        )

    def put_followers_tags_by_id(self, id: str | int, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/followers/{id}/tags".format(id=id)
        return self._client.request(
            method="PUT",
            path=path,
            body=body,
            write=True,
            options=options,
        )

    def put_bots_tags_by_id(self, id: str | int, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/bots/{id}/tags".format(id=id)
        return self._client.request(
            method="PUT",
            path=path,
            body=body,
            write=True,
            options=options,
        )

    def put_emitters_tags_by_id(self, id: str | int, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/emitters/{id}/tags".format(id=id)
        return self._client.request(
            method="PUT",
            path=path,
            body=body,
            write=True,
            options=options,
        )

    def put_portfolios_tags_by_id(self, id: str | int, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/portfolios/{id}/tags".format(id=id)
        return self._client.request(
            method="PUT",
            path=path,
            body=body,
            write=True,
            options=options,
        )

    def patch_tags_by_id(self, id: str | int, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/tags/{id}".format(id=id)
        return self._client.request(
            method="PATCH",
            path=path,
            body=body,
            write=True,
            options=options,
        )

    def delete_tags_by_id(self, id: str | int, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/tags/{id}".format(id=id)
        return self._client.request(
            method="DELETE",
            path=path,
            body=body,
            write=True,
            options=options,
        )

    def put_credentials_by_id(self, id: str | int, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/credentials/{id}".format(id=id)
        return self._client.request(
            method="PUT",
            path=path,
            body=body,
            write=True,
            options=options,
        )

    def delete_credentials_by_id(self, id: str | int, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/credentials/{id}".format(id=id)
        return self._client.request(
            method="DELETE",
            path=path,
            body=body,
            write=True,
            options=options,
        )

    def post_credentials_default_by_id(self, id: str | int, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/credentials/{id}/default".format(id=id)
        return self._client.request(
            method="POST",
            path=path,
            write=True,
            options=options,
        )

    def post_backtest(self, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/backtest"
        return self._client.request(
            method="POST",
            path=path,
            body=body,
            write=True,
            options=options,
        )

    def post_backtest_bulk(self, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/backtest/bulk"
        return self._client.request(
            method="POST",
            path=path,
            body=body,
            write=True,
            options=options,
        )

    def post_backtest_bulk_batches_rerun_by_batch_id(self, batch_id: str | int, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/backtest/bulk/batches/{batch_id}/rerun".format(batch_id=batch_id)
        return self._client.request(
            method="POST",
            path=path,
            write=True,
            options=options,
        )

    def post_backtest_bulk_batches_cancel_by_batch_id(self, batch_id: str | int, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/backtest/bulk/batches/{batch_id}/cancel".format(batch_id=batch_id)
        return self._client.request(
            method="POST",
            path=path,
            write=True,
            options=options,
        )

    def post_backtest_cancel_by_job_id(self, job_id: str | int, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/backtest/{job_id}/cancel".format(job_id=job_id)
        return self._client.request(
            method="POST",
            path=path,
            write=True,
            options=options,
        )

    def post_terminal_placeorder(self, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/terminal/place-order"
        return self._client.request(
            method="POST",
            path=path,
            body=body,
            write=True,
            options=options,
        )

    def post_terminal_cancelorder(self, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/terminal/cancel-order"
        return self._client.request(
            method="POST",
            path=path,
            body=body,
            write=True,
            options=options,
        )

    def get_ai_chat_quota(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/ai/chat/quota"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def get_ai_chat_conversations(self, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/ai/chat/conversations"
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def post_ai_chat_conversations(self, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/ai/chat/conversations"
        return self._client.request(
            method="POST",
            path=path,
            body=body,
            write=True,
            options=options,
        )

    def get_ai_chat_conversations_by_id(self, id: str | int, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/ai/chat/conversations/{id}".format(id=id)
        return self._client.request(
            method="GET",
            path=path,
            options=options,
        )

    def post_ai_chat_conversations_messages_by_id(self, id: str | int, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/ai/chat/conversations/{id}/messages".format(id=id)
        return self._client.request(
            method="POST",
            path=path,
            body=body,
            write=True,
            options=options,
        )

    def post_ai_chat_conversations_tools_confirm_by_id_call_id(self, id: str | int, call_id: str | int, body: JsonValue | None = None, *, options: RequestOptions | None = None) -> JsonValue:
        path = "/api/v1/ai/chat/conversations/{id}/tools/{call_id}/confirm".format(id=id, call_id=call_id)
        return self._client.request(
            method="POST",
            path=path,
            body=body,
            write=True,
            options=options,
        )

